//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaDoZe_WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcademiaDoZe_WPF.Properties.Idioma", typeof(Idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aluno.
        /// </summary>
        public static string AlunoBtn {
            get {
                return ResourceManager.GetString("AlunoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aulas.
        /// </summary>
        public static string Aulasbtn {
            get {
                return ResourceManager.GetString("Aulasbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Avaliação.
        /// </summary>
        public static string AvaliacaoBtn {
            get {
                return ResourceManager.GetString("AvaliacaoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CEP.
        /// </summary>
        public static string cep_Log {
            get {
                return ResourceManager.GetString("cep_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidade.
        /// </summary>
        public static string cidade_log {
            get {
                return ResourceManager.GetString("cidade_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Colaborador.
        /// </summary>
        public static string ColaboradorBtn {
            get {
                return ResourceManager.GetString("ColaboradorBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF.
        /// </summary>
        public static string CPF {
            get {
                return ResourceManager.GetString("CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Frequência.
        /// </summary>
        public static string FrequenciaBtn {
            get {
                return ResourceManager.GetString("FrequenciaBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ENTRAR.
        /// </summary>
        public static string logar {
            get {
                return ResourceManager.GetString("logar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logout.
        /// </summary>
        public static string LOGOUT {
            get {
                return ResourceManager.GetString("LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logradouro.
        /// </summary>
        public static string Logradourobtn {
            get {
                return ResourceManager.GetString("Logradourobtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a País.
        /// </summary>
        public static string pais_Log {
            get {
                return ResourceManager.GetString("pais_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        public static string SenhaBtn {
            get {
                return ResourceManager.GetString("SenhaBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        public static string senhaMain {
            get {
                return ResourceManager.GetString("senhaMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Academia do Zé.
        /// </summary>
        public static string tituloPrincipal {
            get {
                return ResourceManager.GetString("tituloPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Treinos.
        /// </summary>
        public static string treinosbtn {
            get {
                return ResourceManager.GetString("treinosbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FREQUÊNCIA.
        /// </summary>
        public static string txth1Matricula {
            get {
                return ResourceManager.GetString("txth1Matricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Matrícula.
        /// </summary>
        public static string txtMatricula {
            get {
                return ResourceManager.GetString("txtMatricula", resourceCulture);
            }
        }
    }
}
